ALTER TABLE settings ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS notification_preference VARCHAR(255) DEFAULT 'default';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS privacy_level VARCHAR(255) DEFAULT 'public';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT FALSE;
