export enum Permission {
  USER_READ = 'user:read',
  USER_WRITE = 'user:write',
  MFA_MANAGE = 'mfa:manage',
  SESSION_MANAGE = 'session:manage',
  ONTOLOGY_CREATE = 'ontology:create',
  GRAPH_READ = 'graph:read',
  GRAPH_WRITE = 'graph:write',
  RELATIONSHIP_WRITE = 'relationship:write',
  ARTICLE_CREATE = 'article:create',
  ARTICLE_UPDATE = 'article:update',
  ARTICLE_DELETE = 'article:delete',
  ARTICLE_PUBLISH = 'article:publish',
  ARTICLE_APPROVE = 'article:approve',
  SOURCE_CREATE = 'source:create',
  SOURCE_UPDATE = 'source:update',
  SOURCE_DELETE = 'source:delete',
  SOURCE_READ = 'source:read',
}
